# Generated by Django 4.0.4 on 2022-05-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_reviews_movie_theaters'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reservations',
            field=models.ManyToManyField(related_name='reservations', through='reservations.Reservation', to='movies.movietheater'),
        ),
    ]
