# Generated by Django 4.0.4 on 2022-05-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
