# Generated by Django 4.0.4 on 2022-05-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_reservations'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='comments',
            field=models.ManyToManyField(related_name='comments', through='reviews.UserReviewComment', to='users.user'),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='likes',
            field=models.ManyToManyField(related_name='likes', through='reviews.UserReviewLike', to='users.user'),
        ),
    ]
