# Generated by Django 4.0.4 on 2022-05-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_moviereview_comments_moviereview_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='images_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='storage_path',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
