# Generated by Django 4.0.4 on 2022-05-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews', through='reviews.MovieReview', to='users.user'),
        ),
        migrations.AddField(
            model_name='movie',
            name='theaters',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieTheater', to='movies.theater'),
        ),
    ]
