# Generated by Django 4.0.4 on 2022-05-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_reviews_movie_theaters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movietheater',
            name='room',
        ),
        migrations.RemoveField(
            model_name='movietheater',
            name='seat_count',
        ),
    ]
