# Generated by Django 4.0.4 on 2022-05-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movietheater_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='runnning_time',
            new_name='running_time',
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_grade',
            field=models.CharField(max_length=500),
        ),
    ]
