# Generated by Django 4.0.4 on 2022-05-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_runnning_time_movie_running_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movieimage',
            name='stillcut_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movieimage',
            name='storage_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
