# Generated by Django 4.0.4 on 2022-05-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_running_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='stillcut_url',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
